name: CI

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: read

env:
  AWS_REGION: eu-west-2
  SERVICE_NAME: ${{ github.event.repository.name }}
  VALIDATION_ROLE_ARN: arn:aws:iam::020844256789:role/github-actions-create-deployment-role

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run Python quality checks
        uses: thekhoo/github-actions-shared/.github/actions/python-linting@main
        with:
          python-version: 3.13
          directories: speedtest/ tests/
          use-ruff: true
          use-pyrefly: true

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
      - name: Run Python quality checks
        uses: thekhoo/github-actions-shared/.github/actions/python-pytest@main
        with:
          python-version: ${{ matrix.python-version }}
          test-directories: tests/

  # always validate templates whenever a PR is created
  validate-templates:
    name: Validate CloudFormation Templates
    runs-on: ubuntu-latest
    steps:
      - name: Validate templates
        uses: thekhoo/github-actions-shared/.github/actions/validate-cloudformation@main
        with:
          template-paths: infrastructure/deployment-role.yml infrastructure/template.yml
          validation-role-arn: ${{ env.VALIDATION_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
